document.addEventListener('DOMContentLoaded', async () => {
  const defaults = { companyName: "JDE PEET'S", showCompany: true, showName: true, showLogo: false, showFileName: false, showPhoto: false, showAso: false, photoSize: 92, asoSize: 16, primaryColor: '#66783e', secondaryColor: '#dfe8cf', backgroundColor: '#ffffff', textColor: '#17221c', borderColor: '#dfe4d7', borderWidth: 1, radius: 16, spacing: 0, companySize: 22, nameSize: 22, qrSize: 220, alignment: 'center', layoutPreset: 'corporate', positions: { company: { x: 50, y: 34 }, photo: { x: 50, y: 88 }, qr: { x: 50, y: 192 }, name: { x: 50, y: 388 }, aso: { x: 50, y: 430 } } };
  const field = (id) => document.getElementById(id);
  const ids = ['company-name','show-company','show-name','show-logo','show-file','show-photo','show-aso','primary-color','secondary-color','background-color','text-color','border-color','border-width','radius','spacing','company-size','name-size','qr-size','photo-size','aso-size','alignment','company-x','company-y','photo-x','photo-y','qr-x','qr-y','name-x','name-y','aso-x','aso-y'];
  const sample = { id: 'editor-preview', name: 'RAFAEL SILVA', fileName: '343_RAFAEL_SILVA', url: 'https://dmos15.github.io/treinamentos-colaboradores/colaboradores/343_RAFAEL_SILVA.html' };
  const presets = { corporate: { companySize: 22, nameSize: 22, qrSize: 220, spacing: 0, positions: { company: { x: 50, y: 34 }, qr: { x: 50, y: 132 }, name: { x: 50, y: 388 } } }, industrial: { companySize: 24, nameSize: 24, qrSize: 200, spacing: 0, positions: { company: { x: 50, y: 30 }, name: { x: 50, y: 82 }, qr: { x: 50, y: 142 } } }, minimal: { companySize: 18, nameSize: 20, qrSize: 220, spacing: 0, positions: { company: { x: 50, y: 30 }, qr: { x: 50, y: 125 }, name: { x: 50, y: 370 } } }, executive: { companySize: 24, nameSize: 24, qrSize: 210, spacing: 0, positions: { qr: { x: 50, y: 58 }, company: { x: 50, y: 318 }, name: { x: 50, y: 374 } } }, custom: null };
  let settings = { ...defaults, positions: { ...defaults.positions } };
  let currentLayout = null;
  const previewArea = field('editor-preview-area');
  function setFields() { field('company-name').value = settings.companyName || defaults.companyName; field('show-company').checked = settings.showCompany !== false; field('show-name').checked = settings.showName !== false; field('show-logo').checked = Boolean(settings.showLogo); field('show-file').checked = Boolean(settings.showFileName); field('show-photo').checked = Boolean(settings.showPhoto); field('show-aso').checked = Boolean(settings.showAso); [['primary-color', 'primaryColor'], ['secondary-color', 'secondaryColor'], ['background-color', 'backgroundColor'], ['text-color', 'textColor'], ['border-color', 'borderColor']].forEach(([id, key]) => { field(id).value = settings[key] || defaults[key]; }); [['border-width', 'borderWidth'], ['radius', 'radius'], ['spacing', 'spacing'], ['company-size', 'companySize'], ['name-size', 'nameSize'], ['qr-size', 'qrSize'], ['photo-size', 'photoSize'], ['aso-size', 'asoSize']].forEach(([id, key]) => { field(id).value = settings[key] ?? defaults[key]; }); field('alignment').value = settings.alignment || defaults.alignment; ['company','photo','qr','name','aso'].forEach((element) => { field(`${element}-x`).value = settings.positions?.[element]?.x ?? defaults.positions[element].x; field(`${element}-y`).value = settings.positions?.[element]?.y ?? defaults.positions[element].y; }); field('layout-name').value = currentLayout?.nome || ''; field('layout-default').checked = Boolean(currentLayout?.isDefault); document.querySelectorAll('[data-preset]').forEach((button) => button.classList.toggle('active', button.dataset.preset === settings.layoutPreset)); }
  function readSettings() { return { ...settings, companyName: field('company-name').value.trim() || defaults.companyName, showCompany: field('show-company').checked, showName: field('show-name').checked, showLogo: field('show-logo').checked, showFileName: field('show-file').checked, showPhoto: field('show-photo').checked, showAso: field('show-aso').checked, primaryColor: field('primary-color').value, secondaryColor: field('secondary-color').value, backgroundColor: field('background-color').value, textColor: field('text-color').value, borderColor: field('border-color').value, borderWidth: Number(field('border-width').value), radius: Number(field('radius').value), spacing: Number(field('spacing').value), companySize: Number(field('company-size').value), nameSize: Number(field('name-size').value), qrSize: Number(field('qr-size').value), photoSize: Number(field('photo-size').value), asoSize: Number(field('aso-size').value), alignment: field('alignment').value, positions: { company: { x: Number(field('company-x').value), y: Number(field('company-y').value) }, photo: { x: Number(field('photo-x').value), y: Number(field('photo-y').value) }, qr: { x: Number(field('qr-x').value), y: Number(field('qr-y').value) }, name: { x: Number(field('name-x').value), y: Number(field('name-y').value) }, aso: { x: Number(field('aso-x').value), y: Number(field('aso-y').value) } } }; }
  function updateOutputs() { ids.forEach((id) => { const output = field(`${id}-value`); if (output) output.textContent = field(id).value + (id.includes('size') || id.includes('-x') || id.includes('-y') || ['radius','spacing','border-width'].includes(id) ? ' px' : ''); }); }
  function refresh() { settings = readSettings(); previewArea.innerHTML = ''; previewArea.appendChild(createBadgeElement(sample, settings)); updateOutputs(); }
  function parseTemplate(layout) { try { const parsed = JSON.parse(layout.template || '{}'); return { ...defaults, ...parsed, positions: { ...defaults.positions, ...(parsed.positions || {}) } }; } catch { return { ...defaults, positions: { ...defaults.positions } }; } }
  function layoutRecord() { const current = readSettings(); return { id: currentLayout?.id || crypto.randomUUID(), nome: field('layout-name').value.trim() || 'Novo Layout', empresa: current.companyName, mostrarLogo: current.showLogo, logoUrl: current.logoData || '', corPrimaria: current.primaryColor, corSecundaria: current.secondaryColor, qrSize: current.qrSize, template: JSON.stringify(current), criadoEm: currentLayout?.criadoEm || new Date().toISOString(), isDefault: field('layout-default').checked }; }
  function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character])); }
  function renderLayouts() { const layouts = getLayouts(); console.log('Layouts renderizados:', layouts); field('layout-status').textContent = layouts.length ? `${layouts.length} layout(s) compartilhado(s) com a equipe.` : 'Nenhum layout salvo. Crie o primeiro layout da equipe.'; field('layout-list').innerHTML = layouts.map((layout) => `<div class="layout-row"><div><strong>${escapeHtml(layout.nome)}</strong><small>${escapeHtml(layout.empresa || 'Empresa não informada')}</small></div><span class="layout-default">${layout.isDefault ? 'PADRÃO' : ''}</span><div class="layout-actions"><button class="button button-light" data-layout-action="use" data-layout-id="${layout.id}">Usar</button><button class="button button-light" data-layout-action="edit" data-layout-id="${layout.id}">Editar</button><button class="button button-light" data-layout-action="duplicate" data-layout-id="${layout.id}">Duplicar</button><button class="button button-light" data-layout-action="delete" data-layout-id="${layout.id}">Excluir</button></div></div>`).join(''); }
  function editLayout(layout) { currentLayout = layout; settings = parseTemplate(layout); setFields(); refresh(); field('layout-status').textContent = `Editando: ${layout.nome}`; document.querySelector('.editor-layout').scrollIntoView({ behavior: 'smooth', block: 'start' }); field('layout-name').focus({ preventScroll: true }); }
  async function save() { try { const saved = await saveLayout(layoutRecord()); currentLayout = saved.find((layout) => layout.id === (currentLayout?.id || saved[0]?.id)) || saved[0]; activateLayout(currentLayout); renderLayouts(); setFields(); refresh(); field('save-message').textContent = 'Layout salvo e sincronizado com a equipe.'; setTimeout(() => field('save-message').textContent = '', 3000); } catch (error) { field('save-message').textContent = error.message; } }
  document.querySelectorAll('[data-preset]').forEach((button) => button.addEventListener('click', () => { settings = { ...settings, layoutPreset: button.dataset.preset, ...(presets[button.dataset.preset] || {}) }; setFields(); refresh(); }));
  ids.forEach((id) => { field(id).addEventListener('input', refresh); field(id).addEventListener('change', refresh); });
  field('logo-upload').addEventListener('change', (event) => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { settings.logoData = reader.result; refresh(); }; reader.readAsDataURL(file); });
  field('settings-form').addEventListener('submit', (event) => { event.preventDefault(); save(); });
  field('new-layout').addEventListener('click', () => { currentLayout = null; settings = { ...defaults, positions: { ...defaults.positions } }; setFields(); refresh(); });
  field('refresh-layouts').addEventListener('click', async () => { const button = field('refresh-layouts'); button.disabled = true; field('layout-status').textContent = 'Atualizando layouts compartilhados...'; try { await loadLayouts(); renderLayouts(); } catch (error) { console.error('Falha ao carregar layouts compartilhados:', error); field('layout-status').textContent = `Falha ao carregar layouts compartilhados. ${error.message}`; } finally { button.disabled = false; } });
  field('layout-list').addEventListener('click', async (event) => { const button = event.target.closest('[data-layout-action]'); if (!button) return; const layout = getLayouts().find((item) => item.id === button.dataset.layoutId); if (!layout) return; if (button.dataset.layoutAction === 'use') { activateLayout(layout); location.href = `index.html?layout=${encodeURIComponent(layout.id)}`; return; } if (button.dataset.layoutAction === 'edit') { editLayout(layout); return; } if (button.dataset.layoutAction === 'duplicate') { currentLayout = { ...layout, id: crypto.randomUUID(), nome: `${layout.nome} - Cópia`, isDefault: false, criadoEm: new Date().toISOString() }; settings = parseTemplate(layout); setFields(); await save(); return; } if (button.dataset.layoutAction === 'delete' && confirm(`Excluir o layout "${layout.nome}"?`)) { try { await removeLayout(layout.id); if (currentLayout?.id === layout.id) { currentLayout = null; settings = { ...defaults }; setFields(); refresh(); } renderLayouts(); } catch (error) { alert(error.message); } } });
  try { await loadLayouts(); const active = getLayouts().find((layout) => layout.isDefault) || getLayouts()[0]; if (active) editLayout(active); else { setFields(); refresh(); } renderLayouts(); } catch (error) { console.error('Falha ao carregar layouts compartilhados:', error); field('layout-status').textContent = `Falha ao carregar layouts compartilhados. ${error.message}`; setFields(); refresh(); }
});
