const BADGE_DEFAULTS = {
  companyName: "JDE PEET'S", showCompany: true, showName: true, showLogo: false, showFileName: false, showPhoto: false, showAso: false,
  primaryColor: '#66783e', secondaryColor: '#dfe8cf', backgroundColor: '#ffffff', textColor: '#17221c',
  alignment: 'center', borderWidth: 1, borderColor: '#dfe4d7', radius: 16, spacing: 0,
  companySize: 22, nameSize: 22, qrSize: 220, layoutPreset: 'corporate',
  photoSize: 92, asoSize: 16, positions: { company: { x: 50, y: 34 }, photo: { x: 50, y: 88 }, qr: { x: 50, y: 192 }, name: { x: 50, y: 388 }, aso: { x: 50, y: 430 } }
};
function getBadgeSettings() { const saved = window.SHECARD_ACTIVE_LAYOUT || {}; return { ...BADGE_DEFAULTS, ...saved, qrSize: Math.max(100, Math.min(300, Number(saved.qrSize) || BADGE_DEFAULTS.qrSize)), photoSize: Math.max(40, Math.min(180, Number(saved.photoSize) || BADGE_DEFAULTS.photoSize)), asoSize: Math.max(10, Math.min(28, Number(saved.asoSize) || BADGE_DEFAULTS.asoSize)), positions: { ...BADGE_DEFAULTS.positions, ...(saved.positions || {}) } }; }
function renderQr(container, url, size) { container.replaceChildren(); if (!window.QRCode) return; new QRCode(container, { text: url, width: size, height: size, colorDark: '#17221c', colorLight: '#ffffff', correctLevel: QRCode.CorrectLevel.H }); const canvas = container.querySelector('canvas'); const image = container.querySelector('img'); if (canvas) canvas.remove(); if (image) { image.style.display = 'block'; image.width = size; image.height = size; image.alt = 'QR Code'; } }
function horizontalStyle(value, alignment) { if (alignment === 'left' || value < 34) return { alignSelf: 'flex-start', marginLeft: `${Math.max(0, value - 8)}%` }; if (alignment === 'right' || value > 66) return { alignSelf: 'flex-end', marginRight: `${Math.max(0, 92 - value)}%` }; return { alignSelf: 'center', marginLeft: `${value - 50}%` }; }
function applyFlowStyle(element, value, alignment, topMargin) { const horizontal = horizontalStyle(value, alignment); const marginTop = `${Math.max(0, topMargin)}px`; element.style.alignSelf = horizontal.alignSelf; element.style.marginLeft = horizontal.marginLeft || '0'; element.style.marginRight = horizontal.marginRight || '0'; element.style.marginTop = marginTop; element.style.setProperty('--badge-flow-margin', marginTop); }
function createBadgeElement(badge, overrideSettings = null) {
  const settings = overrideSettings ? { ...BADGE_DEFAULTS, ...overrideSettings, positions: { ...BADGE_DEFAULTS.positions, ...(overrideSettings.positions || {}) } } : getBadgeSettings(); const card = document.createElement('article'); card.className = 'badge-card'; card.dataset.badgeId = badge.id;
  card.style.setProperty('--badge-primary', settings.primaryColor); card.style.setProperty('--badge-secondary', settings.secondaryColor); card.style.setProperty('--badge-bg', settings.backgroundColor); card.style.setProperty('--badge-text', settings.textColor); card.style.setProperty('--badge-radius', `${settings.radius}px`); card.style.setProperty('--badge-border-width', `${settings.borderWidth}px`); card.style.setProperty('--badge-border-color', settings.borderColor); card.innerHTML = '<div class="badge-content"><div class="badge-company" data-layout-element="company"></div><div class="badge-photo" data-layout-element="photo"></div><div class="badge-qr" data-layout-element="qr"></div><div class="badge-person" data-layout-element="name"></div><div class="badge-aso" data-layout-element="aso"></div></div>';
  const content = card.querySelector('.badge-content'); const company = card.querySelector('.badge-company'); const photo = card.querySelector('.badge-photo'); const qr = card.querySelector('.badge-qr'); const person = card.querySelector('.badge-person'); const aso = card.querySelector('.badge-aso'); const elements = { company, photo, qr, name: person, aso };
  company.textContent = settings.companyName; person.textContent = badge.name; company.style.fontSize = `${settings.companySize}px`; person.style.fontSize = `${settings.nameSize}px`; company.style.color = settings.primaryColor; person.style.color = settings.textColor; company.style.textAlign = settings.alignment; person.style.textAlign = settings.alignment; if (!settings.showCompany) company.remove(); if (!settings.showName) person.remove();
  if (settings.showPhoto && badge.photoData) { const image = document.createElement('img'); image.src = badge.photoData; image.alt = `Foto de ${badge.name}`; photo.appendChild(image); photo.style.width = `${settings.photoSize}px`; photo.style.height = `${settings.photoSize}px`; } else photo.remove();
  if (settings.showAso && badge.asoValidUntil) { aso.innerHTML = `<span>ASO Válido até:</span><strong>${badge.asoValidUntil}</strong>`; aso.style.fontSize = `${settings.asoSize}px`; aso.style.textAlign = settings.alignment; } else aso.remove();
  const size = Math.max(100, Math.min(300, Number(settings.qrSize) || 220)); qr.style.width = `${size + 20}px`; qr.style.height = `${size + 20}px`; qr.style.setProperty('--badge-qr-size', `${size}px`); renderQr(qr, badge.url, size);
  const order = settings.layoutPreset === 'industrial' ? ['company', 'photo', 'name', 'qr', 'aso'] : settings.layoutPreset === 'executive' ? ['qr', 'company', 'photo', 'name', 'aso'] : ['company', 'photo', 'qr', 'name', 'aso']; order.forEach((key) => { if (elements[key].parentNode) content.appendChild(elements[key]); });
  const yBase = { company: 14, photo: 18, qr: 18, name: 14, aso: 8 }; Object.entries(elements).forEach(([key, element]) => { if (element.parentNode) applyFlowStyle(element, settings.positions[key].x, settings.alignment, Math.max(yBase[key], settings.positions[key].y - (key === 'company' ? 20 : key === 'photo' ? 70 : key === 'qr' ? 132 : key === 'name' ? 368 : 420)) + settings.spacing); });
  if (settings.showLogo) { const logo = document.createElement('img'); logo.className = 'badge-logo'; logo.src = settings.logoData || 'assets/logo.png'; logo.alt = 'Logo'; card.appendChild(logo); } if (settings.showFileName) { const file = document.createElement('small'); file.className = 'badge-file-name'; file.textContent = badge.fileName; card.appendChild(file); } return card;
}
